FROM php:8.2-fpm-alpine
RUN apk add --no-cache postgresql-dev && docker-php-ext-install pdo pdo_pgsql
WORKDIR /var/www/html
COPY . .
RUN composer install --no-dev --optimize-autoloader

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]